# Generated by Django 3.2.6 on 2021-08-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVideoCamaras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoReporte', models.BigIntegerField()),
                ('codigoAlumno', models.BigIntegerField(max_length=20)),
                ('atendio', models.CharField(max_length=30)),
                ('dateSolicitud', models.DateField(verbose_name='date published')),
                ('noCamara', models.BigIntegerField()),
                ('horario', models.CharField(max_length=30)),
                ('hecho', models.CharField(max_length=30)),
                ('fotoIdF', models.CharField(max_length=100)),
                ('fotoIdB', models.CharField(max_length=100)),
            ],
        ),
    ]
