# Generated by Django 3.2.6 on 2021-08-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudvideocamaras',
            name='codigoAlumno',
            field=models.BigIntegerField(),
        ),
    ]
