# Generated by Django 3.2.6 on 2021-09-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0002_alter_solicitudvideocamaras_codigoalumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoReporte', models.BigIntegerField()),
                ('CodigoAlumno', models.BigIntegerField()),
                ('FotoIdF', models.CharField(max_length=30)),
                ('FotoIdB', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
