# Generated by Django 3.2.6 on 2021-09-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0004_eventosocial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FalloCamara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoReporte', models.BigIntegerField()),
                ('NoCamara', models.BigIntegerField()),
                ('Informacion', models.CharField(max_length=20)),
                ('IP', models.CharField(max_length=30)),
                ('SITE', models.CharField(max_length=30)),
                ('Modulo', models.CharField(max_length=20)),
                ('Marca', models.CharField(max_length=20)),
                ('DescFalla', models.CharField(max_length=20)),
                ('Toreos', models.IntegerField()),
                ('MateriaUt', models.CharField(max_length=20)),
                ('Solucionado', models.BooleanField()),
                ('Observaciones', models.CharField(max_length=50)),
            ],
        ),
    ]
