# Generated by Django 3.2.6 on 2021-10-04 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0006_actaadministrativa_alumnos_hojaurgencias_incidencias_pasesalida_rompercandado_users_vistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudvideocamaras',
            name='dateSolicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
