# Generated by Django 3.2.6 on 2021-10-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0007_alter_solicitudvideocamaras_datesolicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actaadministrativa',
            name='CodigoReporte',
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='CodigoReporte',
        ),
        migrations.RemoveField(
            model_name='eventosocial',
            name='CodigoReporte',
        ),
        migrations.RemoveField(
            model_name='fallocamara',
            name='CodigoReporte',
        ),
        migrations.RemoveField(
            model_name='incidencias',
            name='CodigoReporte',
        ),
        migrations.RemoveField(
            model_name='pasesalida',
            name='CodigoReporte',
        ),
        migrations.RemoveField(
            model_name='rompercandado',
            name='CodigoReporte',
        ),
        migrations.RemoveField(
            model_name='solicitudvideocamaras',
            name='codigoReporte',
        ),
        migrations.RemoveField(
            model_name='vistas',
            name='CodigoReporte',
        ),
    ]
