# Generated by Django 3.2.6 on 2021-10-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0008_auto_20211019_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasesalida',
            name='FotoIdB',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='pasesalida',
            name='FotoIdF',
            field=models.ImageField(upload_to=''),
        ),
    ]
