# Generated by Django 3.2.6 on 2021-10-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0011_auto_20211024_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='FotoIdB',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='FotoIdF',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='credencialperdida',
            name='FotoIneFrente',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='credencialperdida',
            name='FotoIneTrasera',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='FotoIdB',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='FotoIdF',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='rompercandado',
            name='FotoIdB',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='rompercandado',
            name='FotoIdF',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='solicitudvideocamaras',
            name='fotoIdB',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='solicitudvideocamaras',
            name='fotoIdF',
            field=models.ImageField(upload_to=''),
        ),
    ]
