# Generated by Django 3.2.6 on 2021-10-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0015_auto_20211026_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='FotoIdB',
            field=models.ImageField(upload_to='BicicletaID'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='FotoIdF',
            field=models.ImageField(upload_to='BicicletaID'),
        ),
        migrations.AlterField(
            model_name='credencialperdida',
            name='FotoIneFrente',
            field=models.ImageField(upload_to='CredencialPerdidaID'),
        ),
        migrations.AlterField(
            model_name='credencialperdida',
            name='FotoIneTrasera',
            field=models.ImageField(upload_to='CredencialPerdidaID'),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='FotoIdB',
            field=models.ImageField(upload_to='IncidenciasID'),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='FotoIdF',
            field=models.ImageField(upload_to='IncidenciasID'),
        ),
        migrations.AlterField(
            model_name='pasesalida',
            name='FotoIdB',
            field=models.ImageField(upload_to='PaseSalidaID'),
        ),
        migrations.AlterField(
            model_name='pasesalida',
            name='FotoIdF',
            field=models.ImageField(upload_to='PaseSalidaID'),
        ),
        migrations.AlterField(
            model_name='rompercandado',
            name='FotoIdB',
            field=models.ImageField(upload_to='RomperCandadoID'),
        ),
        migrations.AlterField(
            model_name='rompercandado',
            name='FotoIdF',
            field=models.ImageField(upload_to='RomperCandadoID'),
        ),
    ]
