# Generated by Django 3.2.6 on 2021-10-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0016_auto_20211026_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencias',
            name='Descripcion',
            field=models.CharField(default='Descripcion', max_length=500),
        ),
        migrations.AddField(
            model_name='reporteincidentesmatpel',
            name='EvidenciaFoto',
            field=models.ImageField(blank=True, upload_to='ReporteIncidentesMatPelID'),
        ),
    ]
