# Generated by Django 3.2.4 on 2021-11-09 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0017_auto_20211029_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaurgencias',
            name='Fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='FechaHora',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='solicitudvideocamaras',
            name='dateSolicitud',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
