# Generated by Django 3.2.4 on 2021-11-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0018_auto_20211109_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencias',
            name='FechaHora',
            field=models.DateTimeField(default=''),
        ),
    ]
