# Generated by Django 3.2.4 on 2021-11-09 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0019_alter_incidencias_fechahora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencias',
            name='FechaHora',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='solicitudvideocamaras',
            name='dateSolicitud',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
